[project]
name = "ukcscraper"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "playwright>=1.49.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.1",
]
